[mgr]
cwd = {
    fg = "#f8f8f2"
}

[indicator]
parent = {
    bg = "#f8f8f2",
    fg = "#000000",
}
current = {
    bg = "#f8f8f2",
    fg = "#000000",
    bold = true
}
preview = {
    fg = "#f8f8f2",
    underline = true
}

[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
overall = { fg = "#f8f8f2", bg = "#000000" }

[filetype]
rules = [
    { mime = "*", fg = "#f8f8f2" }
]

